OPENAI_BASE_PATH: v1/chat/completions
extensions:
  atlassian:
    enabled: false
    type: stdio
    name: atlassian
    description: ''
    cmd: npx
    args:
    - -y
    - mcp-remote
    - https://mcp.atlassian.com/v1/sse
    envs: {}
    env_keys: []
    timeout: 300
    bundled: null
    available_tools: []
  tutorial:
    enabled: false
    type: builtin
    name: tutorial
    description: ''
    display_name: Tutorial
    timeout: 300
    bundled: true
    available_tools: []
  memory:
    enabled: false
    type: builtin
    name: memory
    description: ''
    display_name: Memory
    timeout: 300
    bundled: true
    available_tools: []
  jetbrains:
    enabled: false
    type: builtin
    name: jetbrains
    description: ''
    display_name: Jetbrains
    timeout: 300
    bundled: true
    available_tools: []
  computercontroller:
    enabled: false
    type: builtin
    name: computercontroller
    description: ''
    display_name: Computer Controller
    timeout: 300
    bundled: true
    available_tools: []
  gitlab:
    enabled: true
    type: stdio
    name: gitlab
    description: ''
    cmd: npx
    args:
    - -y
    - '@zereight/mcp-gitlab@latest'
    envs: {}
    env_keys:
    - GITLAB_PERSONAL_ACCESS_TOKEN
    - GITLAB_API_URL
    - GITLAB_READ_ONLY_MODE
    - USE_GITLAB_WIKI
    - USE_MILESTONE
    - USE_PIPELINE
    timeout: 300
    bundled: null
    available_tools: []
  taskmaster:
    enabled: false
    type: stdio
    name: taskmaster
    description: ''
    cmd: npx
    args:
    - -y
    - --package=task-master-ai
    - task-master-ai
    envs: {}
    env_keys:
    - ANTHROPIC_API_KEY
    timeout: 300
    bundled: null
    available_tools: []
  fetch:
    enabled: true
    type: stdio
    name: Fetch
    description: Web content fetching and processing capabilities
    cmd: uvx
    args:
    - mcp-server-fetch
    envs: {}
    env_keys: []
    timeout: 300
    bundled: null
    available_tools: []
  serena:
    enabled: false
    type: stdio
    name: serena
    description: ''
    cmd: uvx
    args:
    - --from
    - git+https://github.com/oraios/serena
    - serena
    - start-mcp-server
    envs: {}
    env_keys: []
    timeout: 300
    bundled: null
    available_tools: []
  playwright:
    enabled: false
    type: stdio
    name: playwright
    description: ''
    cmd: npx
    args:
    - '@playwright/mcp'
    envs: {}
    env_keys: []
    timeout: 300
    bundled: null
    available_tools: []
  claudeskills:
    enabled: true
    type: stdio
    name: claudeskills
    description: Access Claude Skills over MCP
    cmd: uvx
    args:
    - claude-skills-mcp
    - --config
    - /Users/john.daly/tmp/goose/config.json
    envs: {}
    env_keys: []
    timeout: 300
    bundled: null
    available_tools: []
  todo:
    enabled: true
    type: platform
    name: todo
    description: Enable a todo list for Goose so it can keep track of what it is doing
    bundled: true
    available_tools: []
  context7:
    enabled: false
    type: stdio
    name: context7
    description: ''
    cmd: npx
    args:
    - -y
    - '@upstash/context7-mcp'
    envs: {}
    env_keys: []
    timeout: 300
    bundled: null
    available_tools: []
  extensionmanager:
    enabled: false
    type: platform
    name: extensionmanager
    description: Enable extension management tools for discovering, enabling, and disabling extensions
    bundled: true
    available_tools: []
  developer:
    enabled: true
    type: builtin
    name: developer
    description: ''
    display_name: Developer
    timeout: 300
    bundled: true
    available_tools: []
  autovisualiser:
    enabled: false
    type: builtin
    name: autovisualiser
    description: ''
    display_name: Auto Visualiser
    timeout: 300
    bundled: true
    available_tools: []
  obsidian:
    enabled: false
    type: stdio
    name: obsidian
    description: ''
    cmd: uvx
    args:
    - mcp-obsidian
    envs: {}
    env_keys:
    - OBSIDIAN_API_KEY
    - OBSIDIAN_HOST
    timeout: 300
    bundled: null
    available_tools: []
OLLAMA_HOST: http://127.0.0.1:1234
OPENAI_HOST: http://localhost:1234
GOOSE_MODE: auto
GOOSE_PROVIDER: anthropic
GOOSE_MODEL: claude-sonnet-4-5-20250929
ANTHROPIC_HOST: https://api.anthropic.com
